#!/bin/sh
git diff --cached --name-only --diff-filter=ACM doc/evilwm.html | grep -q '' || exit 0
git stash --keep-index
doc/h2m.sh || exit
git add evilwm.1
doc/man2txt.sh evilwm.1 README || exit
git add README
git stash pop
